import hashlib
import tempfile
import unittest
from pathlib import Path

from tests.support import REPOSITORY_ROOT


def tree_digest(root: Path) -> str:
    digest = hashlib.sha256()
    for path in sorted(root.rglob("*")):
        digest.update(path.relative_to(root).as_posix().encode("utf-8"))
        if path.is_file() and not path.is_symlink():
            digest.update(path.read_bytes())
        elif path.is_symlink():
            digest.update(str(path.readlink()).encode("utf-8"))
    return digest.hexdigest()


class DiffTests(unittest.TestCase):
    def load_api(self):
        try:
            from tooling.config.diff import diff
            from tooling.config.render import render
        except ModuleNotFoundError as error:
            self.fail("diff API is missing: {}".format(error))
        return diff, render

    def test_reports_unified_diff_without_mutating_target(self):
        diff, _ = self.load_api()
        with tempfile.TemporaryDirectory() as directory:
            target = Path(directory) / "target"
            target.mkdir()
            (target / "AGENTS.md").write_text("old\n", encoding="utf-8")
            before = tree_digest(target)

            output = diff(REPOSITORY_ROOT, "codex", target)

            self.assertIn("--- target/AGENTS.md", output)
            self.assertIn("+++ rendered/AGENTS.md", output)
            self.assertIn("-old", output)
            self.assertIn("+<!-- Generated by ai-agent-config.", output)
            self.assertEqual(tree_digest(target), before)

    def test_returns_empty_text_for_identical_target(self):
        diff, render = self.load_api()
        with tempfile.TemporaryDirectory() as directory:
            base = Path(directory)
            target = base / "target"
            render(REPOSITORY_ROOT, "gemini", target)

            self.assertEqual(diff(REPOSITORY_ROOT, "gemini", target), "")

    def test_treats_missing_target_file_as_empty(self):
        diff, _ = self.load_api()
        with tempfile.TemporaryDirectory() as directory:
            target = Path(directory) / "target"
            target.mkdir()

            output = diff(REPOSITORY_ROOT, "generic", target)

            self.assertIn("--- target/AGENT_RULES.md", output)
            self.assertIn("+++ rendered/AGENT_RULES.md", output)

    def test_rejects_target_symlink_escape(self):
        diff, _ = self.load_api()
        try:
            from tooling.config.paths import ConfigError
        except ModuleNotFoundError as error:
            self.fail("ConfigError is missing: {}".format(error))
        with tempfile.TemporaryDirectory() as directory:
            base = Path(directory)
            target = base / "target"
            target.mkdir()
            outside = base / "outside.md"
            outside.write_text("outside", encoding="utf-8")
            (target / "CLAUDE.md").symlink_to(outside)

            with self.assertRaisesRegex(ConfigError, "escapes"):
                diff(REPOSITORY_ROOT, "claude", target)


if __name__ == "__main__":
    unittest.main()
