import hashlib
import json
import tempfile
import unittest
from pathlib import Path

from tests.support import REPOSITORY_ROOT


def source_digest(root: Path) -> str:
    digest = hashlib.sha256()
    for path in sorted(root.rglob("*")):
        if not path.is_file() or path.is_symlink():
            continue
        relative = path.relative_to(root)
        if any(part in {".git", ".worktrees", "__pycache__"} for part in relative.parts):
            continue
        if path.suffix == ".pyc" or path.name == ".v2-implementation-plan.md":
            continue
        digest.update(relative.as_posix().encode("utf-8"))
        digest.update(b"\0")
        digest.update(path.read_bytes())
    return digest.hexdigest()


class RenderingTests(unittest.TestCase):
    def load_api(self):
        try:
            from tooling.config.render import render
        except ModuleNotFoundError as error:
            self.fail("render API is missing: {}".format(error))
        return render

    def test_renders_every_adapter_as_a_self_contained_canonical_bundle(self):
        render = self.load_api()
        adapter_ids = ["generic", "codex", "claude", "gemini", "antigravity"]
        with tempfile.TemporaryDirectory() as directory:
            base = Path(directory)
            for adapter_id in adapter_ids:
                with self.subTest(adapter=adapter_id):
                    adapter = json.loads(
                        (REPOSITORY_ROOT / "adapters" / adapter_id / "adapter.json").read_text(encoding="utf-8")
                    )
                    output_root = base / adapter_id

                    rendered = render(REPOSITORY_ROOT, adapter_id, output_root)

                    self.assertEqual(rendered, [output_root.resolve() / adapter["output"]["path"]])
                    body = rendered[0].read_text(encoding="utf-8")
                    self.assertTrue(body.startswith("<!-- Generated by ai-agent-config."))
                    self.assertIn("# Precedence", body)
                    self.assertIn("# Agent Contract", body)
                    self.assertIn("# Project Agent Rules", body)
                    self.assertNotIn("{{CONTENT}}", body)

    def test_repeated_rendering_is_byte_identical(self):
        render = self.load_api()
        with tempfile.TemporaryDirectory() as directory:
            base = Path(directory)

            first = render(REPOSITORY_ROOT, "codex", base / "first")[0]
            second = render(REPOSITORY_ROOT, "codex", base / "second")[0]

            self.assertEqual(first.read_bytes(), second.read_bytes())

    def test_global_render_uses_only_universal_core_and_known_global_path(self):
        render = self.load_api()
        expected_paths = {
            "generic": "AGENT_RULES.md",
            "codex": ".codex/AGENTS.md",
            "claude": ".claude/CLAUDE.md",
            "gemini": ".gemini/GEMINI.md",
            "antigravity": ".gemini/GEMINI.md",
        }
        with tempfile.TemporaryDirectory() as directory:
            base = Path(directory)
            for adapter_id, expected_path in expected_paths.items():
                with self.subTest(adapter=adapter_id):
                    try:
                        rendered = render(
                            REPOSITORY_ROOT,
                            adapter_id,
                            base / adapter_id,
                            scope="global",
                        )
                    except TypeError as error:
                        self.fail("global render scope is missing: {}".format(error))

                    self.assertEqual(
                        rendered,
                        [(base / adapter_id / expected_path).resolve()],
                    )
                    body = rendered[0].read_text(encoding="utf-8")
                    self.assertIn("# Precedence", body)
                    self.assertIn("# Agent Contract", body)
                    self.assertNotIn("# Project Agent Rules", body)

    def test_rendering_does_not_mutate_source(self):
        render = self.load_api()
        before = source_digest(REPOSITORY_ROOT)
        with tempfile.TemporaryDirectory() as directory:
            render(REPOSITORY_ROOT, "claude", Path(directory) / "output")

        self.assertEqual(source_digest(REPOSITORY_ROOT), before)

    def test_rejects_output_below_source_root(self):
        render = self.load_api()
        try:
            from tooling.config.paths import ConfigError
        except ModuleNotFoundError as error:
            self.fail("ConfigError is missing: {}".format(error))

        with self.assertRaisesRegex(ConfigError, "outside the source root"):
            render(REPOSITORY_ROOT, "codex", REPOSITORY_ROOT / "build" / "rendered")

    def test_rejects_destination_symlink_escape(self):
        render = self.load_api()
        try:
            from tooling.config.paths import ConfigError
        except ModuleNotFoundError as error:
            self.fail("ConfigError is missing: {}".format(error))
        with tempfile.TemporaryDirectory() as directory:
            base = Path(directory)
            output = base / "output"
            output.mkdir()
            outside = base / "outside.md"
            outside.write_text("preserve", encoding="utf-8")
            (output / "AGENTS.md").symlink_to(outside)

            with self.assertRaisesRegex(ConfigError, "escapes"):
                render(REPOSITORY_ROOT, "codex", output)

            self.assertEqual(outside.read_text(encoding="utf-8"), "preserve")


if __name__ == "__main__":
    unittest.main()
